baseURL = "https://loicnogu.es"
languageCode = "en-us"
title = "Loïc Nogues: Freelance Web Dev"

[params]
  Description = "Loïc Nogues Freelance Web Developer in Berlin"
  Keywords = "freelance, web, developer, berlin, javascript, react"
  Url = "https://loicnogu.es"

